{% set name = "alibabacloud-adb20211201" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_adb20211201-{{ version }}.tar.gz
  sha256: c11d85a2c08c1dcb58a9629baabba7f18e2f14283894206c1ec44a0304a35cd0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - alibabacloud-tea-util >=0.3.13,<1.0.0
    - alibabacloud-tea-openapi >=0.3.12,<1.0.0
    - alibabacloud-openapi-util >=0.2.2,<1.0.0
    - alibabacloud-endpoint-util >=0.0.3,<1.0.0

test:
  imports:
    - alibabacloud_adb20211201
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aliyun/alibabacloud-python-sdk
  summary: Alibaba Cloud adb (20211201) SDK Library for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
