{% set name = "alibabacloud-adb20211201" %}
{% set version = "1.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_adb20211201-{{ version }}.tar.gz
  sha256: cdef459f760ee230957da15df7b7e919bbf56835d6cafd745d97d11c43262b14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - alibabacloud-tea-util >=0.3.11,<1.0.0
    - alibabacloud-tea-openapi >=0.3.8,<1.0.0
    - alibabacloud-openapi-util >=0.2.1,<1.0.0
    - alibabacloud-endpoint-util >=0.0.3,<1.0.0

test:
  imports:
    - alibabacloud_adb20211201
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aliyun/alibabacloud-python-sdk
  summary: Alibaba Cloud adb (20211201) SDK Library for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
